CALL insertChampion(412, 'Thresh', 'the Chain Warden', 'Support', 'Fighter');
CALL insertChampion(266, 'Aatrox', 'the Darkin Blade', 'Fighter', 'Tank');
CALL insertChampion(23, 'Tryndamere', 'the Barbarian King', 'Fighter', 'Assassin');
CALL insertChampion(79, 'Gragas', 'the Rabble Rouser', 'Fighter', 'Mage');
CALL insertChampion(69, 'Cassiopeia', 'the Serpent&#039;s Embrace', 'Mage', '');
CALL insertChampion(78, 'Poppy', 'the Iron Ambassador', 'Fighter', 'Assassin');
CALL insertChampion(13, 'Ryze', 'the Rogue Mage', 'Mage', 'Fighter');
CALL insertChampion(14, 'Sion', 'The Undead Juggernaut', 'Tank', 'Fighter');
CALL insertChampion(1, 'Annie', 'the Dark Child', 'Mage', '');
CALL insertChampion(43, 'Karma', 'the Enlightened One', 'Mage', 'Support');
CALL insertChampion(111, 'Nautilus', 'the Titan of the Depths', 'Tank', 'Fighter');
CALL insertChampion(99, 'Lux', 'the Lady of Luminosity', 'Mage', 'Support');
CALL insertChampion(103, 'Ahri', 'the Nine-Tailed Fox', 'Mage', 'Assassin');
CALL insertChampion(2, 'Olaf', 'the Berserker', 'Fighter', 'Tank');
CALL insertChampion(112, 'Viktor', 'the Machine Herald', 'Mage', '');
CALL insertChampion(34, 'Anivia', 'the Cryophoenix', 'Mage', 'Support');
CALL insertChampion(86, 'Garen', 'The Might of Demacia', 'Fighter', 'Tank');
CALL insertChampion(27, 'Singed', 'the Mad Chemist', 'Tank', 'Fighter');
CALL insertChampion(127, 'Lissandra', 'the Ice Witch', 'Mage', '');
CALL insertChampion(57, 'Maokai', 'the Twisted Treant', 'Tank', 'Mage');
CALL insertChampion(25, 'Morgana', 'Fallen Angel', 'Mage', 'Support');
CALL insertChampion(28, 'Evelynn', 'the Widowmaker', 'Assassin', 'Mage');
CALL insertChampion(105, 'Fizz', 'the Tidal Trickster', 'Assassin', 'Fighter');
CALL insertChampion(238, 'Zed', 'the Master of Shadows', 'Assassin', 'Fighter');
CALL insertChampion(74, 'Heimerdinger', 'the Revered Inventor', 'Mage', 'Support');
CALL insertChampion(68, 'Rumble', 'the Mechanized Menace', 'Fighter', 'Mage');
CALL insertChampion(82, 'Mordekaiser', 'the Master of Metal', 'Fighter', 'Mage');
CALL insertChampion(37, 'Sona', 'Maven of the Strings', 'Support', 'Mage');
CALL insertChampion(55, 'Katarina', 'the Sinister Blade', 'Assassin', 'Mage');
CALL insertChampion(96, 'Kog&#039;Maw', 'the Mouth of the Abyss', 'Marksman', 'Mage');
CALL insertChampion(22, 'Ashe', 'the Frost Archer', 'Marksman', 'Support');
CALL insertChampion(117, 'Lulu', 'the Fae Sorceress', 'Support', 'Mage');
CALL insertChampion(30, 'Karthus', 'the Deathsinger', 'Mage', '');
CALL insertChampion(12, 'Alistar', 'the Minotaur', 'Tank', 'Suppport');
CALL insertChampion(122, 'Darius', 'the Hand of Noxus', 'Fighter', 'Tank');
CALL insertChampion(67, 'Vayne', 'the Night Hunter', 'Marksman', 'Assassin');
CALL insertChampion(110, 'Varus', 'the Arrow of Retribution', 'Marksman', 'Mage');
CALL insertChampion(77, 'Udyr', 'the Spirit Walker', 'Fighter', 'Tank');
CALL insertChampion(126, 'Jayce', 'the Defender of Tomorrow', 'Fighter', 'Marksman');
CALL insertChampion(89, 'Leona', 'the Radiant Dawn', 'Tank', 'Support');
CALL insertChampion(134, 'Syndra', 'the Dark Sovereign', 'Mage', 'Support');
CALL insertChampion(80, 'Pantheon', 'the Artisan of War', 'Fighter', 'Assassin');
CALL insertChampion(121, 'Kha&#039;Zix', 'the Voidreaver', 'Assassin', 'Fighter');
CALL insertChampion(92, 'Riven', 'the Exile', 'Fighter', 'Assassin');
CALL insertChampion(42, 'Corki', 'the Daring Bombardier', 'Marksman', '');
CALL insertChampion(268, 'Azir', 'the Emperor of the Sands', 'Mage', 'Marksman');
CALL insertChampion(51, 'Caitlyn', 'the Sheriff of Piltover', 'Marksman', '');
CALL insertChampion(76, 'Nidalee', 'the Bestial Huntress', 'Assassin', 'Fighter');
CALL insertChampion(3, 'Galio', 'the Sentinel&#039;s Sorrow', 'Tank', 'Mage');
CALL insertChampion(85, 'Kennen', 'the Heart of the Tempest', 'Mage', 'Marksman');
CALL insertChampion(45, 'Veigar', 'the Tiny Master of Evil', 'Mage', '');
CALL insertChampion(432, 'Bard', 'the Wandering Caretaker', 'Support', 'Mage');
CALL insertChampion(150, 'Gnar', 'the Missing Link', 'Fighter', 'Marksman');
CALL insertChampion(104, 'Graves', 'the Outlaw', 'Marksman', '');
CALL insertChampion(90, 'Malzahar', 'the Prophet of the Void', 'Mage', 'Assassin');
CALL insertChampion(254, 'Vi', 'the Piltover Enforcer', 'Fighter', 'Assassin');
CALL insertChampion(10, 'Kayle', 'The Judicator', 'Fighter', 'Support');
CALL insertChampion(39, 'Irelia', 'the Will of the Blades', 'Fighter', 'Assassin');
CALL insertChampion(64, 'Lee Sin', 'the Blind Monk', 'Fighter', 'Assassin');
CALL insertChampion(60, 'Elise', 'The Spider Queen', 'Mage', 'Fighter');
CALL insertChampion(106, 'Volibear', 'the Thunder&#039;s Roar', 'Fighter', 'Tank');
CALL insertChampion(20, 'Nunu', 'the Yeti Rider', 'Support', 'Fighter');
CALL insertChampion(4, 'Twisted Fate', 'the Card Master', 'Mage', '');
CALL insertChampion(24, 'Jax', 'Grandmaster at Arms', 'Fighter', 'Assassin');
CALL insertChampion(102, 'Shyvana', 'the Half-Dragon', 'Fighter', 'Tank');
CALL insertChampion(429, 'Kalista', 'the Spear of Vengeance', 'Marksman', '');
CALL insertChampion(36, 'Dr. Mundo', 'the Madman of Zaun', 'Fighter', 'Tank');
CALL insertChampion(63, 'Brand', 'the Burning Vengeance', 'Mage', '');
CALL insertChampion(131, 'Diana', 'Scorn of the Moon', 'Fighter', 'Mage');
CALL insertChampion(113, 'Sejuani', 'the Winter&#039;s Wrath', 'Tank', 'Fighter');
CALL insertChampion(8, 'Vladimir', 'the Crimson Reaper', 'Mage', 'Tank');
CALL insertChampion(154, 'Zac', 'the Secret Weapon', 'Tank', 'Fighter');
CALL insertChampion(421, 'Rek&#039;Sai', 'the Void Burrower', 'Fighter', '');
CALL insertChampion(133, 'Quinn', 'Demacia&#039;s Wings', 'Marksman', 'Fighter');
CALL insertChampion(84, 'Akali', 'the Fist of Shadow', 'Assassin', '');
CALL insertChampion(18, 'Tristana', 'the Yordle Gunner', 'Marksman', 'Assassin');
CALL insertChampion(120, 'Hecarim', 'the Shadow of War', 'Fighter', 'Tank');
CALL insertChampion(15, 'Sivir', 'the Battle Mistress', 'Marksman', '');
CALL insertChampion(236, 'Lucian', 'the Purifier', 'Marksman', '');
CALL insertChampion(107, 'Rengar', 'the Pridestalker', 'Assassin', 'Fighter');
CALL insertChampion(19, 'Warwick', 'the Blood Hunter', 'Fighter', 'Tank');
CALL insertChampion(72, 'Skarner', 'the Crystal Vanguard', 'Fighter', 'Tank');
CALL insertChampion(54, 'Malphite', 'Shard of the Monolith', 'Tank', 'Fighter');
CALL insertChampion(157, 'Yasuo', 'the Unforgiven', 'Fighter', 'Assassin');
CALL insertChampion(101, 'Xerath', 'the Magus Ascendant', 'Mage', 'Assassin');
CALL insertChampion(17, 'Teemo', 'the Swift Scout', 'Marksman', 'Assassin');
CALL insertChampion(75, 'Nasus', 'the Curator of the Sands', 'Fighter', 'Tank');
CALL insertChampion(58, 'Renekton', 'the Butcher of the Sands', 'Fighter', 'Tank');
CALL insertChampion(119, 'Draven', 'the Glorious Executioner', 'Marksman', '');
CALL insertChampion(35, 'Shaco', 'the Demon Jester', 'Assassin', '');
CALL insertChampion(50, 'Swain', 'the Master Tactician', 'Mage', 'Fighter');
CALL insertChampion(115, 'Ziggs', 'the Hexplosives Expert', 'Mage', '');
CALL insertChampion(40, 'Janna', 'the Storm&#039;s Fury', 'Support', 'Mage');
CALL insertChampion(91, 'Talon', 'the Blade&#039;s Shadow', 'Assassin', 'Fighter');
CALL insertChampion(61, 'Orianna', 'the Lady of Clockwork', 'Mage', 'Support');
CALL insertChampion(9, 'Fiddlesticks', 'the Harbinger of Doom', 'Mage', 'Support');
CALL insertChampion(114, 'Fiora', 'the Grand Duelist', 'Fighter', 'Assassin');
CALL insertChampion(31, 'Cho&#039;Gath', 'the Terror of the Void', 'Tank', 'Mage');
CALL insertChampion(33, 'Rammus', 'the Armordillo', 'Tank', 'Fighter');
CALL insertChampion(7, 'LeBlanc', 'the Deceiver', 'Assassin', 'Mage');
CALL insertChampion(26, 'Zilean', 'the Chronokeeper', 'Support', 'Mage');
CALL insertChampion(16, 'Soraka', 'the Starchild', 'Support', 'Mage');
CALL insertChampion(56, 'Nocturne', 'the Eternal Nightmare', 'Assassin', 'Fighter');
CALL insertChampion(222, 'Jinx', 'the Loose Cannon', 'Marksman', '');
CALL insertChampion(83, 'Yorick', 'the Gravedigger', 'Fighter', 'Mage');
CALL insertChampion(6, 'Urgot', 'the Headsman&#039;s Pride', 'Marksman', 'Fighter');
CALL insertChampion(21, 'Miss Fortune', 'the Bounty Hunter', 'Marksman', '');
CALL insertChampion(62, 'Wukong', 'the Monkey King', 'Fighter', 'Tank');
CALL insertChampion(53, 'Blitzcrank', 'the Great Steam Golem', 'Tank', 'Fighter');
CALL insertChampion(98, 'Shen', 'Eye of Twilight', 'Tank', 'Fighter');
CALL insertChampion(201, 'Braum', 'the Heart of the Freljord', 'Support', 'Tank');
CALL insertChampion(5, 'Xin Zhao', 'the Seneschal of Demacia', 'Fighter', 'Assassin');
CALL insertChampion(29, 'Twitch', 'the Plague Rat', 'Marksman', 'Assassin');
CALL insertChampion(11, 'Master Yi', 'the Wuju Bladesman', 'Assassin', 'Fighter');
CALL insertChampion(44, 'Taric', 'the Gem Knight', 'Support', 'Fighter');
CALL insertChampion(32, 'Amumu', 'the Sad Mummy', 'Tank', 'Mage');
CALL insertChampion(41, 'Gangplank', 'the Saltwater Scourge', 'Fighter', 'Support');
CALL insertChampion(48, 'Trundle', 'the Troll King', 'Fighter', 'Tank');
CALL insertChampion(38, 'Kassadin', 'the Void Walker', 'Assassin', 'Mage');
CALL insertChampion(161, 'Vel&#039;Koz', 'the Eye of the Void', 'Mage', '');
CALL insertChampion(143, 'Zyra', 'Rise of the Thorns', 'Mage', 'Support');
CALL insertChampion(267, 'Nami', 'the Tidecaller', 'Support', 'Mage');
CALL insertChampion(59, 'Jarvan IV', 'the Exemplar of Demacia', 'Tank', 'Fighter');
CALL insertChampion(81, 'Ezreal', 'the Prodigal Explorer', 'Marksman', 'Mage');
