CALL insert_champion(412, 'Thresh', 'the Chain Warden', 'Support', 'Fighter', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Thresh.png');
CALL insert_champion(266, 'Aatrox', 'the Darkin Blade', 'Fighter', 'Tank', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Aatrox.png');
CALL insert_champion(23, 'Tryndamere', 'the Barbarian King', 'Fighter', 'Assassin', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Tryndamere.png');
CALL insert_champion(79, 'Gragas', 'the Rabble Rouser', 'Fighter', 'Mage', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Gragas.png');
CALL insert_champion(69, 'Cassiopeia', 'the Serpent&#039;s Embrace', 'Mage', 'undefined', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Cassiopeia.png');
CALL insert_champion(78, 'Poppy', 'the Iron Ambassador', 'Fighter', 'Assassin', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Poppy.png');
CALL insert_champion(13, 'Ryze', 'the Rogue Mage', 'Mage', 'Fighter', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Ryze.png');
CALL insert_champion(14, 'Sion', 'The Undead Juggernaut', 'Tank', 'Fighter', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Sion.png');
CALL insert_champion(1, 'Annie', 'the Dark Child', 'Mage', 'undefined', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Annie.png');
CALL insert_champion(43, 'Karma', 'the Enlightened One', 'Mage', 'Support', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Karma.png');
CALL insert_champion(111, 'Nautilus', 'the Titan of the Depths', 'Tank', 'Fighter', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Nautilus.png');
CALL insert_champion(99, 'Lux', 'the Lady of Luminosity', 'Mage', 'Support', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Lux.png');
CALL insert_champion(103, 'Ahri', 'the Nine-Tailed Fox', 'Mage', 'Assassin', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Ahri.png');
CALL insert_champion(2, 'Olaf', 'the Berserker', 'Fighter', 'Tank', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Olaf.png');
CALL insert_champion(112, 'Viktor', 'the Machine Herald', 'Mage', 'undefined', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Viktor.png');
CALL insert_champion(34, 'Anivia', 'the Cryophoenix', 'Mage', 'Support', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Anivia.png');
CALL insert_champion(86, 'Garen', 'The Might of Demacia', 'Fighter', 'Tank', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Garen.png');
CALL insert_champion(27, 'Singed', 'the Mad Chemist', 'Tank', 'Fighter', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Singed.png');
CALL insert_champion(127, 'Lissandra', 'the Ice Witch', 'Mage', 'undefined', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Lissandra.png');
CALL insert_champion(57, 'Maokai', 'the Twisted Treant', 'Tank', 'Mage', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Maokai.png');
CALL insert_champion(25, 'Morgana', 'Fallen Angel', 'Mage', 'Support', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Morgana.png');
CALL insert_champion(28, 'Evelynn', 'the Widowmaker', 'Assassin', 'Mage', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Evelynn.png');
CALL insert_champion(105, 'Fizz', 'the Tidal Trickster', 'Assassin', 'Fighter', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Fizz.png');
CALL insert_champion(238, 'Zed', 'the Master of Shadows', 'Assassin', 'Fighter', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Zed.png');
CALL insert_champion(74, 'Heimerdinger', 'the Revered Inventor', 'Mage', 'Support', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Heimerdinger.png');
CALL insert_champion(68, 'Rumble', 'the Mechanized Menace', 'Fighter', 'Mage', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Rumble.png');
CALL insert_champion(82, 'Mordekaiser', 'the Master of Metal', 'Fighter', 'Mage', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Mordekaiser.png');
CALL insert_champion(37, 'Sona', 'Maven of the Strings', 'Support', 'Mage', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Sona.png');
CALL insert_champion(55, 'Katarina', 'the Sinister Blade', 'Assassin', 'Mage', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Katarina.png');
CALL insert_champion(96, 'Kog&#039;Maw', 'the Mouth of the Abyss', 'Marksman', 'Mage', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/KogMaw.png');
CALL insert_champion(22, 'Ashe', 'the Frost Archer', 'Marksman', 'Support', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Ashe.png');
CALL insert_champion(117, 'Lulu', 'the Fae Sorceress', 'Support', 'Mage', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Lulu.png');
CALL insert_champion(30, 'Karthus', 'the Deathsinger', 'Mage', 'undefined', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Karthus.png');
CALL insert_champion(12, 'Alistar', 'the Minotaur', 'Tank', 'Suppport', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Alistar.png');
CALL insert_champion(122, 'Darius', 'the Hand of Noxus', 'Fighter', 'Tank', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Darius.png');
CALL insert_champion(67, 'Vayne', 'the Night Hunter', 'Marksman', 'Assassin', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Vayne.png');
CALL insert_champion(110, 'Varus', 'the Arrow of Retribution', 'Marksman', 'Mage', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Varus.png');
CALL insert_champion(77, 'Udyr', 'the Spirit Walker', 'Fighter', 'Tank', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Udyr.png');
CALL insert_champion(126, 'Jayce', 'the Defender of Tomorrow', 'Fighter', 'Marksman', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Jayce.png');
CALL insert_champion(89, 'Leona', 'the Radiant Dawn', 'Tank', 'Support', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Leona.png');
CALL insert_champion(134, 'Syndra', 'the Dark Sovereign', 'Mage', 'Support', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Syndra.png');
CALL insert_champion(80, 'Pantheon', 'the Artisan of War', 'Fighter', 'Assassin', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Pantheon.png');
CALL insert_champion(121, 'Kha&#039;Zix', 'the Voidreaver', 'Assassin', 'Fighter', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Khazix.png');
CALL insert_champion(92, 'Riven', 'the Exile', 'Fighter', 'Assassin', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Riven.png');
CALL insert_champion(42, 'Corki', 'the Daring Bombardier', 'Marksman', 'undefined', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Corki.png');
CALL insert_champion(268, 'Azir', 'the Emperor of the Sands', 'Mage', 'Marksman', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Azir.png');
CALL insert_champion(51, 'Caitlyn', 'the Sheriff of Piltover', 'Marksman', 'undefined', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Caitlyn.png');
CALL insert_champion(76, 'Nidalee', 'the Bestial Huntress', 'Assassin', 'Fighter', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Nidalee.png');
CALL insert_champion(3, 'Galio', 'the Sentinel&#039;s Sorrow', 'Tank', 'Mage', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Galio.png');
CALL insert_champion(85, 'Kennen', 'the Heart of the Tempest', 'Mage', 'Marksman', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Kennen.png');
CALL insert_champion(45, 'Veigar', 'the Tiny Master of Evil', 'Mage', 'undefined', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Veigar.png');
CALL insert_champion(432, 'Bard', 'the Wandering Caretaker', 'Support', 'Mage', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Bard.png');
CALL insert_champion(150, 'Gnar', 'the Missing Link', 'Fighter', 'Marksman', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Gnar.png');
CALL insert_champion(104, 'Graves', 'the Outlaw', 'Marksman', 'undefined', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Graves.png');
CALL insert_champion(90, 'Malzahar', 'the Prophet of the Void', 'Mage', 'Assassin', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Malzahar.png');
CALL insert_champion(254, 'Vi', 'the Piltover Enforcer', 'Fighter', 'Assassin', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Vi.png');
CALL insert_champion(10, 'Kayle', 'The Judicator', 'Fighter', 'Support', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Kayle.png');
CALL insert_champion(39, 'Irelia', 'the Will of the Blades', 'Fighter', 'Assassin', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Irelia.png');
CALL insert_champion(64, 'Lee Sin', 'the Blind Monk', 'Fighter', 'Assassin', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/LeeSin.png');
CALL insert_champion(60, 'Elise', 'The Spider Queen', 'Mage', 'Fighter', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Elise.png');
CALL insert_champion(106, 'Volibear', 'the Thunder&#039;s Roar', 'Fighter', 'Tank', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Volibear.png');
CALL insert_champion(20, 'Nunu', 'the Yeti Rider', 'Support', 'Fighter', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Nunu.png');
CALL insert_champion(4, 'Twisted Fate', 'the Card Master', 'Mage', 'undefined', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/TwistedFate.png');
CALL insert_champion(24, 'Jax', 'Grandmaster at Arms', 'Fighter', 'Assassin', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Jax.png');
CALL insert_champion(102, 'Shyvana', 'the Half-Dragon', 'Fighter', 'Tank', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Shyvana.png');
CALL insert_champion(429, 'Kalista', 'the Spear of Vengeance', 'Marksman', 'undefined', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Kalista.png');
CALL insert_champion(36, 'Dr. Mundo', 'the Madman of Zaun', 'Fighter', 'Tank', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/DrMundo.png');
CALL insert_champion(63, 'Brand', 'the Burning Vengeance', 'Mage', 'undefined', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Brand.png');
CALL insert_champion(131, 'Diana', 'Scorn of the Moon', 'Fighter', 'Mage', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Diana.png');
CALL insert_champion(113, 'Sejuani', 'the Winter&#039;s Wrath', 'Tank', 'Fighter', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Sejuani.png');
CALL insert_champion(8, 'Vladimir', 'the Crimson Reaper', 'Mage', 'Tank', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Vladimir.png');
CALL insert_champion(154, 'Zac', 'the Secret Weapon', 'Tank', 'Fighter', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Zac.png');
CALL insert_champion(421, 'Rek&#039;Sai', 'the Void Burrower', 'Fighter', 'undefined', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/RekSai.png');
CALL insert_champion(133, 'Quinn', 'Demacia&#039;s Wings', 'Marksman', 'Fighter', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Quinn.png');
CALL insert_champion(84, 'Akali', 'the Fist of Shadow', 'Assassin', 'undefined', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Akali.png');
CALL insert_champion(18, 'Tristana', 'the Yordle Gunner', 'Marksman', 'Assassin', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Tristana.png');
CALL insert_champion(120, 'Hecarim', 'the Shadow of War', 'Fighter', 'Tank', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Hecarim.png');
CALL insert_champion(15, 'Sivir', 'the Battle Mistress', 'Marksman', 'undefined', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Sivir.png');
CALL insert_champion(236, 'Lucian', 'the Purifier', 'Marksman', 'undefined', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Lucian.png');
CALL insert_champion(107, 'Rengar', 'the Pridestalker', 'Assassin', 'Fighter', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Rengar.png');
CALL insert_champion(19, 'Warwick', 'the Blood Hunter', 'Fighter', 'Tank', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Warwick.png');
CALL insert_champion(72, 'Skarner', 'the Crystal Vanguard', 'Fighter', 'Tank', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Skarner.png');
CALL insert_champion(54, 'Malphite', 'Shard of the Monolith', 'Tank', 'Fighter', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Malphite.png');
CALL insert_champion(157, 'Yasuo', 'the Unforgiven', 'Fighter', 'Assassin', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Yasuo.png');
CALL insert_champion(101, 'Xerath', 'the Magus Ascendant', 'Mage', 'Assassin', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Xerath.png');
CALL insert_champion(17, 'Teemo', 'the Swift Scout', 'Marksman', 'Assassin', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Teemo.png');
CALL insert_champion(75, 'Nasus', 'the Curator of the Sands', 'Fighter', 'Tank', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Nasus.png');
CALL insert_champion(58, 'Renekton', 'the Butcher of the Sands', 'Fighter', 'Tank', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Renekton.png');
CALL insert_champion(119, 'Draven', 'the Glorious Executioner', 'Marksman', 'undefined', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Draven.png');
CALL insert_champion(35, 'Shaco', 'the Demon Jester', 'Assassin', 'undefined', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Shaco.png');
CALL insert_champion(50, 'Swain', 'the Master Tactician', 'Mage', 'Fighter', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Swain.png');
CALL insert_champion(115, 'Ziggs', 'the Hexplosives Expert', 'Mage', 'undefined', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Ziggs.png');
CALL insert_champion(40, 'Janna', 'the Storm&#039;s Fury', 'Support', 'Mage', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Janna.png');
CALL insert_champion(91, 'Talon', 'the Blade&#039;s Shadow', 'Assassin', 'Fighter', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Talon.png');
CALL insert_champion(61, 'Orianna', 'the Lady of Clockwork', 'Mage', 'Support', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Orianna.png');
CALL insert_champion(9, 'Fiddlesticks', 'the Harbinger of Doom', 'Mage', 'Support', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/FiddleSticks.png');
CALL insert_champion(114, 'Fiora', 'the Grand Duelist', 'Fighter', 'Assassin', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Fiora.png');
CALL insert_champion(31, 'Cho&#039;Gath', 'the Terror of the Void', 'Tank', 'Mage', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Chogath.png');
CALL insert_champion(33, 'Rammus', 'the Armordillo', 'Tank', 'Fighter', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Rammus.png');
CALL insert_champion(7, 'LeBlanc', 'the Deceiver', 'Assassin', 'Mage', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Leblanc.png');
CALL insert_champion(26, 'Zilean', 'the Chronokeeper', 'Support', 'Mage', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Zilean.png');
CALL insert_champion(16, 'Soraka', 'the Starchild', 'Support', 'Mage', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Soraka.png');
CALL insert_champion(56, 'Nocturne', 'the Eternal Nightmare', 'Assassin', 'Fighter', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Nocturne.png');
CALL insert_champion(222, 'Jinx', 'the Loose Cannon', 'Marksman', 'undefined', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Jinx.png');
CALL insert_champion(83, 'Yorick', 'the Gravedigger', 'Fighter', 'Mage', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Yorick.png');
CALL insert_champion(6, 'Urgot', 'the Headsman&#039;s Pride', 'Marksman', 'Fighter', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Urgot.png');
CALL insert_champion(21, 'Miss Fortune', 'the Bounty Hunter', 'Marksman', 'undefined', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/MissFortune.png');
CALL insert_champion(62, 'Wukong', 'the Monkey King', 'Fighter', 'Tank', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/MonkeyKing.png');
CALL insert_champion(53, 'Blitzcrank', 'the Great Steam Golem', 'Tank', 'Fighter', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Blitzcrank.png');
CALL insert_champion(98, 'Shen', 'Eye of Twilight', 'Tank', 'Fighter', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Shen.png');
CALL insert_champion(201, 'Braum', 'the Heart of the Freljord', 'Support', 'Tank', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Braum.png');
CALL insert_champion(5, 'Xin Zhao', 'the Seneschal of Demacia', 'Fighter', 'Assassin', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/XinZhao.png');
CALL insert_champion(29, 'Twitch', 'the Plague Rat', 'Marksman', 'Assassin', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Twitch.png');
CALL insert_champion(11, 'Master Yi', 'the Wuju Bladesman', 'Assassin', 'Fighter', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/MasterYi.png');
CALL insert_champion(44, 'Taric', 'the Gem Knight', 'Support', 'Fighter', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Taric.png');
CALL insert_champion(32, 'Amumu', 'the Sad Mummy', 'Tank', 'Mage', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Amumu.png');
CALL insert_champion(41, 'Gangplank', 'the Saltwater Scourge', 'Fighter', 'Support', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Gangplank.png');
CALL insert_champion(48, 'Trundle', 'the Troll King', 'Fighter', 'Tank', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Trundle.png');
CALL insert_champion(38, 'Kassadin', 'the Void Walker', 'Assassin', 'Mage', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Kassadin.png');
CALL insert_champion(161, 'Vel&#039;Koz', 'the Eye of the Void', 'Mage', 'undefined', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Velkoz.png');
CALL insert_champion(143, 'Zyra', 'Rise of the Thorns', 'Mage', 'Support', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Zyra.png');
CALL insert_champion(267, 'Nami', 'the Tidecaller', 'Support', 'Mage', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Nami.png');
CALL insert_champion(59, 'Jarvan IV', 'the Exemplar of Demacia', 'Tank', 'Fighter', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/JarvanIV.png');
CALL insert_champion(81, 'Ezreal', 'the Prodigal Explorer', 'Marksman', 'Mage', 'http://ddragon.leagueoflegends.com/cdn/5.2.1/img/champion/Ezreal.png');
