CALL insertChampion('412', 'Thresh', 'the Chain Warden', 'Thresh.png', 'Support', 'Fighter');
CALL insertChampion('266', 'Aatrox', 'the Darkin Blade', 'Aatrox.png', 'Fighter', 'Tank');
CALL insertChampion('23', 'Tryndamere', 'the Barbarian King', 'Tryndamere.png', 'Fighter', 'Assassin');
CALL insertChampion('79', 'Gragas', 'the Rabble Rouser', 'Gragas.png', 'Fighter', 'Mage');
CALL insertChampion('69', 'Cassiopeia', 'the Serpent&#039;s Embrace', 'Cassiopeia.png', 'Mage', 'NULL');
CALL insertChampion('78', 'Poppy', 'the Iron Ambassador', 'Poppy.png', 'Fighter', 'Assassin');
CALL insertChampion('13', 'Ryze', 'the Rogue Mage', 'Ryze.png', 'Mage', 'Fighter');
CALL insertChampion('14', 'Sion', 'The Undead Juggernaut', 'Sion.png', 'Tank', 'Fighter');
CALL insertChampion('1', 'Annie', 'the Dark Child', 'Annie.png', 'Mage', 'NULL');
CALL insertChampion('43', 'Karma', 'the Enlightened One', 'Karma.png', 'Mage', 'Support');
CALL insertChampion('111', 'Nautilus', 'the Titan of the Depths', 'Nautilus.png', 'Tank', 'Fighter');
CALL insertChampion('99', 'Lux', 'the Lady of Luminosity', 'Lux.png', 'Mage', 'Support');
CALL insertChampion('103', 'Ahri', 'the Nine-Tailed Fox', 'Ahri.png', 'Mage', 'Assassin');
CALL insertChampion('2', 'Olaf', 'the Berserker', 'Olaf.png', 'Fighter', 'Tank');
CALL insertChampion('112', 'Viktor', 'the Machine Herald', 'Viktor.png', 'Mage', 'NULL');
CALL insertChampion('34', 'Anivia', 'the Cryophoenix', 'Anivia.png', 'Mage', 'Support');
CALL insertChampion('86', 'Garen', 'The Might of Demacia', 'Garen.png', 'Fighter', 'Tank');
CALL insertChampion('27', 'Singed', 'the Mad Chemist', 'Singed.png', 'Tank', 'Fighter');
CALL insertChampion('127', 'Lissandra', 'the Ice Witch', 'Lissandra.png', 'Mage', 'NULL');
CALL insertChampion('57', 'Maokai', 'the Twisted Treant', 'Maokai.png', 'Tank', 'Mage');
CALL insertChampion('25', 'Morgana', 'Fallen Angel', 'Morgana.png', 'Mage', 'Support');
CALL insertChampion('28', 'Evelynn', 'the Widowmaker', 'Evelynn.png', 'Assassin', 'Mage');
CALL insertChampion('105', 'Fizz', 'the Tidal Trickster', 'Fizz.png', 'Assassin', 'Fighter');
CALL insertChampion('238', 'Zed', 'the Master of Shadows', 'Zed.png', 'Assassin', 'Fighter');
CALL insertChampion('74', 'Heimerdinger', 'the Revered Inventor', 'Heimerdinger.png', 'Mage', 'Support');
CALL insertChampion('68', 'Rumble', 'the Mechanized Menace', 'Rumble.png', 'Fighter', 'Mage');
CALL insertChampion('82', 'Mordekaiser', 'the Master of Metal', 'Mordekaiser.png', 'Fighter', 'Mage');
CALL insertChampion('37', 'Sona', 'Maven of the Strings', 'Sona.png', 'Support', 'Mage');
CALL insertChampion('55', 'Katarina', 'the Sinister Blade', 'Katarina.png', 'Assassin', 'Mage');
CALL insertChampion('96', 'Kog&#039;Maw', 'the Mouth of the Abyss', 'KogMaw.png', 'Marksman', 'Mage');
CALL insertChampion('22', 'Ashe', 'the Frost Archer', 'Ashe.png', 'Marksman', 'Support');
CALL insertChampion('117', 'Lulu', 'the Fae Sorceress', 'Lulu.png', 'Support', 'Mage');
CALL insertChampion('30', 'Karthus', 'the Deathsinger', 'Karthus.png', 'Mage', 'NULL');
CALL insertChampion('12', 'Alistar', 'the Minotaur', 'Alistar.png', 'Tank', 'Suppport');
CALL insertChampion('122', 'Darius', 'the Hand of Noxus', 'Darius.png', 'Fighter', 'Tank');
CALL insertChampion('67', 'Vayne', 'the Night Hunter', 'Vayne.png', 'Marksman', 'Assassin');
CALL insertChampion('110', 'Varus', 'the Arrow of Retribution', 'Varus.png', 'Marksman', 'Mage');
CALL insertChampion('77', 'Udyr', 'the Spirit Walker', 'Udyr.png', 'Fighter', 'Tank');
CALL insertChampion('126', 'Jayce', 'the Defender of Tomorrow', 'Jayce.png', 'Fighter', 'Marksman');
CALL insertChampion('89', 'Leona', 'the Radiant Dawn', 'Leona.png', 'Tank', 'Support');
CALL insertChampion('134', 'Syndra', 'the Dark Sovereign', 'Syndra.png', 'Mage', 'Support');
CALL insertChampion('80', 'Pantheon', 'the Artisan of War', 'Pantheon.png', 'Fighter', 'Assassin');
CALL insertChampion('121', 'Kha&#039;Zix', 'the Voidreaver', 'Khazix.png', 'Assassin', 'Fighter');
CALL insertChampion('92', 'Riven', 'the Exile', 'Riven.png', 'Fighter', 'Assassin');
CALL insertChampion('42', 'Corki', 'the Daring Bombardier', 'Corki.png', 'Marksman', 'NULL');
CALL insertChampion('268', 'Azir', 'the Emperor of the Sands', 'Azir.png', 'Mage', 'Marksman');
CALL insertChampion('51', 'Caitlyn', 'the Sheriff of Piltover', 'Caitlyn.png', 'Marksman', 'NULL');
CALL insertChampion('76', 'Nidalee', 'the Bestial Huntress', 'Nidalee.png', 'Assassin', 'Fighter');
CALL insertChampion('3', 'Galio', 'the Sentinel&#039;s Sorrow', 'Galio.png', 'Tank', 'Mage');
CALL insertChampion('85', 'Kennen', 'the Heart of the Tempest', 'Kennen.png', 'Mage', 'Marksman');
CALL insertChampion('45', 'Veigar', 'the Tiny Master of Evil', 'Veigar.png', 'Mage', 'NULL');
CALL insertChampion('432', 'Bard', 'the Wandering Caretaker', 'Bard.png', 'Support', 'Mage');
CALL insertChampion('150', 'Gnar', 'the Missing Link', 'Gnar.png', 'Fighter', 'Marksman');
CALL insertChampion('104', 'Graves', 'the Outlaw', 'Graves.png', 'Marksman', 'NULL');
CALL insertChampion('90', 'Malzahar', 'the Prophet of the Void', 'Malzahar.png', 'Mage', 'Assassin');
CALL insertChampion('254', 'Vi', 'the Piltover Enforcer', 'Vi.png', 'Fighter', 'Assassin');
CALL insertChampion('10', 'Kayle', 'The Judicator', 'Kayle.png', 'Fighter', 'Support');
CALL insertChampion('39', 'Irelia', 'the Will of the Blades', 'Irelia.png', 'Fighter', 'Assassin');
CALL insertChampion('64', 'Lee Sin', 'the Blind Monk', 'LeeSin.png', 'Fighter', 'Assassin');
CALL insertChampion('60', 'Elise', 'The Spider Queen', 'Elise.png', 'Mage', 'Fighter');
CALL insertChampion('106', 'Volibear', 'the Thunder&#039;s Roar', 'Volibear.png', 'Fighter', 'Tank');
CALL insertChampion('20', 'Nunu', 'the Yeti Rider', 'Nunu.png', 'Support', 'Fighter');
CALL insertChampion('4', 'Twisted Fate', 'the Card Master', 'TwistedFate.png', 'Mage', 'NULL');
CALL insertChampion('24', 'Jax', 'Grandmaster at Arms', 'Jax.png', 'Fighter', 'Assassin');
CALL insertChampion('102', 'Shyvana', 'the Half-Dragon', 'Shyvana.png', 'Fighter', 'Tank');
CALL insertChampion('429', 'Kalista', 'the Spear of Vengeance', 'Kalista.png', 'Marksman', 'NULL');
CALL insertChampion('36', 'Dr. Mundo', 'the Madman of Zaun', 'DrMundo.png', 'Fighter', 'Tank');
CALL insertChampion('63', 'Brand', 'the Burning Vengeance', 'Brand.png', 'Mage', 'NULL');
CALL insertChampion('131', 'Diana', 'Scorn of the Moon', 'Diana.png', 'Fighter', 'Mage');
CALL insertChampion('113', 'Sejuani', 'the Winter&#039;s Wrath', 'Sejuani.png', 'Tank', 'Fighter');
CALL insertChampion('8', 'Vladimir', 'the Crimson Reaper', 'Vladimir.png', 'Mage', 'Tank');
CALL insertChampion('154', 'Zac', 'the Secret Weapon', 'Zac.png', 'Tank', 'Fighter');
CALL insertChampion('421', 'Rek&#039;Sai', 'the Void Burrower', 'RekSai.png', 'Fighter', 'NULL');
CALL insertChampion('133', 'Quinn', 'Demacia&#039;s Wings', 'Quinn.png', 'Marksman', 'Fighter');
CALL insertChampion('84', 'Akali', 'the Fist of Shadow', 'Akali.png', 'Assassin', 'NULL');
CALL insertChampion('18', 'Tristana', 'the Yordle Gunner', 'Tristana.png', 'Marksman', 'Assassin');
CALL insertChampion('120', 'Hecarim', 'the Shadow of War', 'Hecarim.png', 'Fighter', 'Tank');
CALL insertChampion('15', 'Sivir', 'the Battle Mistress', 'Sivir.png', 'Marksman', 'NULL');
CALL insertChampion('236', 'Lucian', 'the Purifier', 'Lucian.png', 'Marksman', 'NULL');
CALL insertChampion('107', 'Rengar', 'the Pridestalker', 'Rengar.png', 'Assassin', 'Fighter');
CALL insertChampion('19', 'Warwick', 'the Blood Hunter', 'Warwick.png', 'Fighter', 'Tank');
CALL insertChampion('72', 'Skarner', 'the Crystal Vanguard', 'Skarner.png', 'Fighter', 'Tank');
CALL insertChampion('54', 'Malphite', 'Shard of the Monolith', 'Malphite.png', 'Tank', 'Fighter');
CALL insertChampion('157', 'Yasuo', 'the Unforgiven', 'Yasuo.png', 'Fighter', 'Assassin');
CALL insertChampion('101', 'Xerath', 'the Magus Ascendant', 'Xerath.png', 'Mage', 'Assassin');
CALL insertChampion('17', 'Teemo', 'the Swift Scout', 'Teemo.png', 'Marksman', 'Assassin');
CALL insertChampion('75', 'Nasus', 'the Curator of the Sands', 'Nasus.png', 'Fighter', 'Tank');
CALL insertChampion('58', 'Renekton', 'the Butcher of the Sands', 'Renekton.png', 'Fighter', 'Tank');
CALL insertChampion('119', 'Draven', 'the Glorious Executioner', 'Draven.png', 'Marksman', 'NULL');
CALL insertChampion('35', 'Shaco', 'the Demon Jester', 'Shaco.png', 'Assassin', 'NULL');
CALL insertChampion('50', 'Swain', 'the Master Tactician', 'Swain.png', 'Mage', 'Fighter');
CALL insertChampion('115', 'Ziggs', 'the Hexplosives Expert', 'Ziggs.png', 'Mage', 'NULL');
CALL insertChampion('40', 'Janna', 'the Storm&#039;s Fury', 'Janna.png', 'Support', 'Mage');
CALL insertChampion('91', 'Talon', 'the Blade&#039;s Shadow', 'Talon.png', 'Assassin', 'Fighter');
CALL insertChampion('61', 'Orianna', 'the Lady of Clockwork', 'Orianna.png', 'Mage', 'Support');
CALL insertChampion('9', 'Fiddlesticks', 'the Harbinger of Doom', 'FiddleSticks.png', 'Mage', 'Support');
CALL insertChampion('114', 'Fiora', 'the Grand Duelist', 'Fiora.png', 'Fighter', 'Assassin');
CALL insertChampion('31', 'Cho&#039;Gath', 'the Terror of the Void', 'Chogath.png', 'Tank', 'Mage');
CALL insertChampion('33', 'Rammus', 'the Armordillo', 'Rammus.png', 'Tank', 'Fighter');
CALL insertChampion('7', 'LeBlanc', 'the Deceiver', 'Leblanc.png', 'Assassin', 'Mage');
CALL insertChampion('26', 'Zilean', 'the Chronokeeper', 'Zilean.png', 'Support', 'Mage');
CALL insertChampion('16', 'Soraka', 'the Starchild', 'Soraka.png', 'Support', 'Mage');
CALL insertChampion('56', 'Nocturne', 'the Eternal Nightmare', 'Nocturne.png', 'Assassin', 'Fighter');
CALL insertChampion('222', 'Jinx', 'the Loose Cannon', 'Jinx.png', 'Marksman', 'NULL');
CALL insertChampion('83', 'Yorick', 'the Gravedigger', 'Yorick.png', 'Fighter', 'Mage');
CALL insertChampion('6', 'Urgot', 'the Headsman&#039;s Pride', 'Urgot.png', 'Marksman', 'Fighter');
CALL insertChampion('21', 'Miss Fortune', 'the Bounty Hunter', 'MissFortune.png', 'Marksman', 'NULL');
CALL insertChampion('62', 'Wukong', 'the Monkey King', 'MonkeyKing.png', 'Fighter', 'Tank');
CALL insertChampion('53', 'Blitzcrank', 'the Great Steam Golem', 'Blitzcrank.png', 'Tank', 'Fighter');
CALL insertChampion('98', 'Shen', 'Eye of Twilight', 'Shen.png', 'Tank', 'Fighter');
CALL insertChampion('201', 'Braum', 'the Heart of the Freljord', 'Braum.png', 'Support', 'Tank');
CALL insertChampion('5', 'Xin Zhao', 'the Seneschal of Demacia', 'XinZhao.png', 'Fighter', 'Assassin');
CALL insertChampion('29', 'Twitch', 'the Plague Rat', 'Twitch.png', 'Marksman', 'Assassin');
CALL insertChampion('11', 'Master Yi', 'the Wuju Bladesman', 'MasterYi.png', 'Assassin', 'Fighter');
CALL insertChampion('44', 'Taric', 'the Gem Knight', 'Taric.png', 'Support', 'Fighter');
CALL insertChampion('32', 'Amumu', 'the Sad Mummy', 'Amumu.png', 'Tank', 'Mage');
CALL insertChampion('41', 'Gangplank', 'the Saltwater Scourge', 'Gangplank.png', 'Fighter', 'Support');
CALL insertChampion('48', 'Trundle', 'the Troll King', 'Trundle.png', 'Fighter', 'Tank');
CALL insertChampion('38', 'Kassadin', 'the Void Walker', 'Kassadin.png', 'Assassin', 'Mage');
CALL insertChampion('161', 'Vel&#039;Koz', 'the Eye of the Void', 'Velkoz.png', 'Mage', 'NULL');
CALL insertChampion('143', 'Zyra', 'Rise of the Thorns', 'Zyra.png', 'Mage', 'Support');
CALL insertChampion('267', 'Nami', 'the Tidecaller', 'Nami.png', 'Support', 'Mage');
CALL insertChampion('59', 'Jarvan IV', 'the Exemplar of Demacia', 'JarvanIV.png', 'Tank', 'Fighter');
CALL insertChampion('81', 'Ezreal', 'the Prodigal Explorer', 'Ezreal.png', 'Marksman', 'Mage');
